name: cron job scheduler
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  database-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh active cluster nodes every 15 minutes
        if: github.event.schedule == '*/15 * * * *'
        run: |
          curl --request POST \
          --url 'https://dag-orbit.vercel.app/api/schedule'
